### ISSUE TITLE
Should live-region read anything for pop-ups? 

### ISSUE THREAD

**Issue by nwisehart** [Esri/a11y-map#13]

**Comment by kellyhutchins** [comment]
I don't think we need live regions to read any popup content and screen readers should already let users know about the dialog since the popup has role=dialog.
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/dialog_role

**Comment by Malvoz** [comment]
Focus is also delegated to popups, which is a sufficient technique to ensure the content is announced by screen readers when opened.

I suggest closing this issue.
